# Generated by Django 3.0.5 on 2020-04-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donator',
            old_name='user_id',
            new_name='user',
        ),
    ]
