# Generated by Django 3.0.5 on 2020-04-25 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_auto_20200423_1050'),
        ('donator', '0002_auto_20200423_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_description', models.CharField(max_length=550)),
                ('is_approved', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.datetime(2020, 4, 25, 18, 25, 2, 447056))),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donator.Donator')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiver.Receiver')),
            ],
        ),
    ]
