# Generated by Django 3.0.5 on 2020-04-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='sub_county_id',
            new_name='sub_county',
        ),
        migrations.RenameField(
            model_name='subcounty',
            old_name='county_id',
            new_name='county',
        ),
    ]
